### ISSUE TITLE
current package is really old - when will you publish new package

### ISSUE THREAD

**Issue by shay314** [conda-forge/sagemaker-python-sdk-feedstock#18]
Issue:
The current sagemaker package is really old - more than 7 months old - can you please update it?
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by rluria14** [comment]
@shay314 thank you, v1.71.0 has been added.

**Comment by shay314** [comment]
@rluria14 - thank you very much for the fast reply and action.
