### ISSUE TITLE
Why two sagemaker feedstocks?

### ISSUE THREAD

**Issue by bretttully** [conda-forge/sagemaker-python-sdk-feedstock#228]
### Comment:

I am just curious why there are two sagemaker feedstocks?

* https://github.com/conda-forge/sagemaker-feedstock
* https://github.com/conda-forge/sagemaker-python-sdk-feedstock

Is there any reason to preference one over the other?

**Comment by bretttully** [comment]
Also asked on the other repo: https://github.com/conda-forge/sagemaker-feedstock/issues/39

**Comment by claytonparnell** [comment]
This one (https://github.com/conda-forge/sagemaker-python-sdk-feedstock/) is maintained by AWS and is recommended. Both were community started, and this was the one we were able to become maintainers on 🙂.
